application: avy-project
version: 1
runtime: go
api_version: go1

handlers:
# www
- url: /css
  static_dir: client/css
- url: /img
  static_dir: client/img
- url: /js
  static_dir: client/js
- url: /libs
  static_dir: client/libs
- url: /partials
  static_dir: client/partials
# anif
- url: /framework
  static_dir: anif/framework
# common
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
- url: /.*
  script: _go_app